name: tms
description: tms project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bootstrap_icons: ^1.5.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  device_info_plus: ^8.0.0
  dropdown_button2: ^1.8.9
  email_validator: ^2.1.17
  encrypt: ^5.0.1
  expandable: ^5.0.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.5
  # flutter_launcher_icons: ^0.10.0
  flutter_inappwebview: ^5.7.2+2
  flutter_local_notifications: ^12.0.3
  # flutter_native_splash: ^2.2.5
  flutter_svg: ^1.0.3
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  image: ^3.1.1
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  image_picker_android: ^0.8.5+3
  intl: ^0.17.0
  loading_indicator: ^3.1.0
  logger: ^1.1.0
  mask_text_input_formatter: ^2.0.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  responsive_framework: ^0.2.0
  syncfusion_flutter_pdfviewer: ^20.3.59
  uni_links: ^0.5.1
  url_launcher: ^6.1.3
  video_player: ^2.4.9
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf

    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

# flutter_icons:
#   # flutter pub run flutter_launcher_icons:main

#   # android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/icon.jpg"

# flutter_native_splash:
#   # flutter pub run flutter_native_splash:create
#   # flutter pub run flutter_native_splash:remove

#   color: "#ffffff"
#   image: assets/images/splash.png

#   # android_gravity can be one of the following Android Gravity (see
#   # https://developer.android.com/reference/android/view/Gravity): bottom, center,
#   # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
#   # fill_vertical, left, right, start, or top.
#   android_gravity: fill|clip_horizontal|clip_vertical
#   #
#   # ios_content_mode can be one of the following iOS UIView.ContentMode (see
#   # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
#   # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
#   # bottomLeft, or bottomRight.
#   ios_content_mode: scaleAspectFit

#   android_screen_orientation: portrait